LATENT_DIM = 100
NUM_EPOCHS = 100
BATCH_SIZE = 32
THRESHOLD = 0.9

# RNN in latent vector generator
HIDDEN_SIZE = 100
NUM_LAYERS = 2

MUSIC_LENGTH = 64 * 3
DO_DATA_FILTRATION = True
FILTRATION_THRESHOLD = 0.05
BASIC_LENGTH = 64
SEQUENCE_LENGTH = MUSIC_LENGTH / BASIC_LENGTH
INFO_INTERVAL_EPOCHS = 2

# For Data
NUMBER_OF_PITCHES = 72
LOWEST_PITCH = 24
MAESTRO_PATH = "C://Users/mateu/Desktop/INZYNIERKA/data/midi/maestro-v3.0.0"
MAESTRO_FILE_EXTENSION = '*.midi'
LPD_PATH = 'D:/LPD_5'
LPD_FILE_EXTENSION = '*.npz'